services:
  - type: web
    name: amortizacao-financeira
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: GA4_ID
        value: G-J6CQG19L6Z
      - key: ADSENSE_CLIENT
        value: ca-pub-6191460191140933
      - key: WHATSAPP_NUMBER
        value: 5551989840198
      - key: SITE_DOMAIN
        value: amortizacao-financeira.onrender.com
      - key: ADMIN_TOKEN
        sync: false
