name = "amortizacao-financeira"
compatibility_date = "2026-06-01"

pages_build_output_dir = "."

[vars]
GA4_ID = "G-J6CQG19L6Z"
ADSENSE_CLIENT = "ca-pub-6191460191140933"
WHATSAPP_NUMBER = "5551989840198"
SITE_DOMAIN = "calculadoramortizacao.com.br"
ADMIN_TOKEN = "31721006ed760661bb061299b6899f14280a3b4e7d0759b9c63cfa5d3841b825"

[[kv_namespaces]]
binding = "LEADS"
id = ""
